# Site settings
permalink: /:title
title: 向应昌
header-img: img/home-bg.jpg
email: lovecvoice@gmail.com
description: "Good things take time and patience."
baseurl: ""
url: "http://xiangyingchang.com"
twitter_username: 
github_username:  
facebook_username:  

# Build settings
markdown: kramdown
highlighter: rouge
# permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sitemap:
  lastmod: 2015-12-23
  priority: 0.7
  changefreq: 'monthly'
  exclude: 'yes'
  
